workflows:
  pack-ipk-testapp:
    instance_type: mac_mini
    environment:
      xcode: 13.3
    scripts: 
      - name: build and upload to testapp.io
        script: |
          bundle install
          bundle exec fastlane ios development --verbose
