workflows:
  pack-ipk-testapp:
    instance_type: mac_mini_m1
    environment:
      xcode: 13.3
      groups:
        - default
    scripts: 
      - name: build and upload to testapp.io
        script: |
          bundle install
          bundle exec fastlane ios development --verbose
