version: 2.1

jobs:
  build:
    macos:
      xcode: 13.2.1	 # Specify the Xcode version to use
    steps:
      - checkout
      - run: gem install bundler:2.3.3
      - run: bundle install
      - run: bundle exec fastlane ios development
workflows:
  sample: 
    jobs:
      - build
